TowNews.WebUI/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using TopNews.Core.DTOS.Category;
using TopNews.Core.DTOS.Post;
using TopNews.Core.Interfaces;
using TopNews.Core.Services;
using TopNews.Core.Validation.Category;
using X.PagedList;

namespace TopNews.WebUI.Controllers
{
    [Authorize]
    public class CategoryController : Controller
    {
        private readonly ICategoryService _categoryService;
        private readonly IPostService _postService;

        public CategoryController(ICategoryService categoryService, IPostService postService)
        {
            _categoryService = categoryService;
            _postService = postService;
        }
        public async Task<IActionResult> Index()
        {
            var result = await _categoryService.GetAll();
            return View(result);
        }
        public async Task<IActionResult> AddNew()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddNew(CategoryDTO model)
        {
            var validator = new CreateValidation();
            var validationResult = await validator.ValidateAsync(model);
            if (validationResult.IsValid)
            {
                var result = await _categoryService.GetByName(model);
                if (!result.Success)
                {
                    ViewBag.AuthError = "Category exists.";
                    return View(model);
                }
                await _categoryService.Create(model);
                return RedirectToAction(nameof(Index));
            }
            ViewBag.AuthError = validationResult.Errors[0];
            return View(model);
        }
        public async Task<IActionResult> Delete(int id)
        {
            var categoryDto = await _categoryService.Get(id);

            if (categoryDto == null)
            {
                ViewBag.AuthError = "Category not found.";
                return View();
            }

            List<PostDTO> posts = await _postService.GetByCategory(id);
            ViewBag.CategoryName = categoryDto.Name;
            ViewBag.CategoryId = categoryDto.Id;

            int pageSize = 20;
            int pageNumber = 1;
            return View("Delete", posts.ToPagedList(pageNumber, pageSize));
        }
        public async Task<IActionResult> DeleteCategory(int id)
        {
            var categoryDto = await _categoryService.Get(id);
            if (categoryDto == null)
            {
                ViewBag.AuthError = "Category not found.";
                return View();
            }
            await _categoryService.Delete(id);
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Edit(int id)
        {
            var result = await _categoryService.Get(id);
            return View(result);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(CategoryDTO model)
        {
            var validator = new CreateValidation();
            var validationResult = await validator.ValidateAsync(model);
            if (validationResult.IsValid)
            {
                await _categoryService.Update(model);
                return RedirectToAction(nameof(Index));
            }
            ViewBag.AuthError = validationResult.Errors[0];
            return View(model);
        }
    }
}

TowNews.WebUI/Controllers/DashboardController.cs
using AutoMapper;
using FluentValidation;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using TopNews.Core.DTOS.User;
using TopNews.Core.Entities.User;
using TopNews.Core.Services;
using TopNews.Core.Validation.User;
using TopNews.WebUI.Models.ViewModels;

namespace TopNews.WebUI.Controllers
{
    [Authorize]
    public class DashboardController : Controller
    {
        private readonly UserService _userService;
        public DashboardController(UserService userService)
        {
            _userService = userService;
        }

        public IActionResult Index()
        {
            return View();
        }
        [AllowAnonymous]// GET
        public IActionResult Login()
        {
            var ipAddress = HttpContext.Connection.RemoteIpAddress?.ToString();

            var user =  HttpContext.User.Identity.IsAuthenticated;
            if (user)
            {
                return RedirectToAction(nameof(Index));
            }
            return View();
        }
        [AllowAnonymous]// POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(UserLoginDTO model)
        {
            

            var validator = new UserLoginValidation();
            var validationResult = validator.Validate(model);
            if (validationResult.IsValid)
            {
                ServiceResponse result = await _userService.LoginUserAsync(model);
                if(result.Success)
                {
                    return RedirectToAction(nameof(Index));
                }

                ViewBag.AuthError = result.Message;
                return View(model);
            }
            ViewBag.AuthError = validationResult.Errors[0];
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> Logout()
        {
            await _userService.SingOutUserAsync();
            return RedirectToAction(nameof(Login));
        }
        public async Task<IActionResult> GetAll()
        {
            var result  = await _userService.GetAllAsync();
            return View(result.Payload);
        }
        public async Task<IActionResult> Profile(string Id)
        {
            var result = await _userService.GetUserByIdAsync(Id);
            if (result.Success)
            {
                UpdateProfileVM profile = new UpdateProfileVM()
                {
                    UserInfo = (UpdateUserDTO)result.Payload
                };
                return View(profile);
            }
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Profile(UpdatePasswordDTO pass)
        {
            var validator = new UpdatePasswordVilidation();
            var validationReuslt = await validator.ValidateAsync(pass);
            if (validationReuslt.IsValid)
            {
                var result = await _userService.ChangePasswordAsync(pass.Id, pass.OldPassword, pass.NewPassword);
                if (result.Success)
                {
                    return View(result.Payload); 
                }

                ViewBag.UpdatePasswordError = result.Payload;
                return View();
            }
            ViewBag.UpdatePasswordError = validationReuslt.Errors[0];
            return View();

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateUser(UpdateUserDTO user)
        {
            var validator = new UpdateUserValidation();
            var validationReuslt = await validator.ValidateAsync(user);
            if (validationReuslt.IsValid)
            {
                //var result = await _userService.ChangePasswordAsync(pass.Id, pass.OldPassword, pass.NewPassword);
                //if (result.Success)
                //{
                //    return View(result.Payload);
                //}

                //ViewBag.UpdatePasswordError = result.Payload;
                //return View();
            }
            ViewBag.UpdatePasswordError = validationReuslt.Errors[0];

            var result = user.FirstName;

            return View();

        }
        public async Task<IActionResult> AddNew()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddNew(CreateUserDTO model)
        {
            var validator = new CreateUserValidation();
            var validationReuslt = await validator.ValidateAsync(model);
            if (validationReuslt.IsValid)
            {
                var result = await _userService.AddNewUserAsync(model);
                if (result.Success)
                {
                    return RedirectToAction(nameof(GetAll));
                }
                else
                {
                    ViewBag.CreateUserError = result.Payload;
                    return View();
                }
            }
            ViewBag.CreateUserValidationError = validationReuslt.Errors[0];
            return View();
        }
        public async Task<IActionResult> Delete(string id)
        {
            var result = await _userService.GetUserByIdAsync(id);
            return View(result.Payload);
        }
        public async Task<IActionResult> DeleteUser(string id)
        {
            var result = await _userService.DeleteUserAsync(id);
            if (result.Success)
            {
                return RedirectToAction(nameof(GetAll));
            }
            ViewBag.CreateUserError = result.Errors.Count() > 0 ? ((IdentityError)result.Errors.First()).Description : result.Message;
            return RedirectToAction(nameof(GetAll));
        }
        [AllowAnonymous]
        public async Task<IActionResult> ConfirmEmail(string userId, string token)
        {
            var result = await _userService.ConfirmEmailAsync(userId, token);
            return RedirectToAction(nameof(Login));
        }
        [AllowAnonymous]
        public async Task<IActionResult> ForgotPassword()
        {
            return View();
        }
        [AllowAnonymous]
        [HttpPost]
        public async Task<IActionResult> ForgotPassword(string email)
        {
            var result = await _userService.ForgotPasswordAsync(email);
            if (result.Success)
            {
                ViewBag.AuthError = "We send you email to reset the password.";
                return View(nameof(Login));
            }
            return View();
        }
        [AllowAnonymous]
        public async Task<IActionResult> ResetPassword(string email, string token)
        {
            ViewBag.Email = email;
            ViewBag.Token = token;
            return View();
        }
        [AllowAnonymous]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ResetPassword(ResetPasswordDTO model)
        {
            if (model.Password != model.ConfirmPassword)
            {
                ViewBag.AuthError = "New password must be equel to confirmed password";
                return View();
            }
            var result = await _userService.ResetPasswordAsync(model);
            ViewBag.AuthError = result.Message;
            return View(nameof(Login));
        }
        private async Task LoadRoles()
        {
            var result = await _userService.GetAllRoles();
            /*@ViewBag.RoleList = new SelectList((System.Collections.IEnumerable)result, nameof(IdentityRole.Id),nameof(IdentityRole.Name));*/
            @ViewBag.RoleList = result;
        }
        public async Task<IActionResult> Edit(string id)
        {
            await LoadRoles();
            var user = await _userService.GetUserForEditAsync(id);
            if (user.Success)
            {
                return View(user.Payload);
            }
            return View();
        }
        [ValidateAntiForgeryToken]
        [HttpPost]
        public async Task<IActionResult> Edit(EditUserDTO model)
        {
            var validator = new EditUserValidation();
            var validationResult = await validator.ValidateAsync(model);
            if (validationResult.IsValid)
            {
                var result = await _userService.EditUser(model);
                return View(nameof(Index));
            }

            await LoadRoles();
            ViewBag.AuthError = validationResult.Errors[0];
            return View(nameof(Edit));
        }
    }
}

TowNews.WebUI/Views/Shared/Dashboard/_Footer.cshtml
 <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->

  <!-- Main Footer -->
  <footer class="main-footer">
    <strong>Copyright &copy; 2014-2021 <a href="https://adminlte.io">AdminLTE.io</a>.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
      <b>Version</b> 3.2.0
    </div>
  </footer>
<!-- ./wrapper -->

TowNews.WebUI/Views/Shared/Dashboard/_FooterIncludes.cshtml
<!-- REQUIRED SCRIPTS -->

<!-- jQuery -->
<script src="~/dashboard/plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap -->
<script src="~/dashboard/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- AdminLTE -->
<script src="~/dashboard/js/adminlte.js"></script>

<!-- OPTIONAL SCRIPTS -->
<script src="~/dashboard/plugins/chart.js/Chart.min.js"></script>
<!-- AdminLTE for demo purposes -->
<!--<script src="~/dashboard/js/demo.js"></script>-->
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="~/dashboard/js/pages/dashboard3.js"></script>

TowNews.WebUI/Views/Shared/Dashboard/_Header.cshtml
<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>AdminLTE 3 | Dashboard 3</title>

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome Icons -->
<link rel="stylesheet" href="~/dashboard/plugins/fontawesome-free/css/all.min.css">
  <!-- IonIcons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="~/dashboard/css/adminlte.min.css">

TowNews.WebUI/Views/Shared/Dashboard/_NavBar.cshtml
@using Microsoft.AspNetCore.Identity;
@using TopNews.Core.Entities.User;
@inject UserManager<AppUser> UserManager

@{
    var user = await UserManager.GetUserAsync(User);
}
<!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a asp-controller="Home" asp-action="Index" class="nav-link">Home</a>
        </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
        <li class="nav-item">
            <a asp-action="Profile" asp-route-id="@user.Id" class="btn btn-primary ml-2">Profile</a>
        </li>
        <li class="nav-item ml-2">
            <form method="post" asp-action="Logout">
                <button class="btn btn-primary" type="submit">Log out</button>
            </form>
        </li>
    </ul>
</nav>
<!-- /.navbar -->

TowNews.WebUI/Views/Shared/Dashboard/_SideBar.cshtml
 <!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="index3.html" class="brand-link">
        <img src="~/Dashboard/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
        <span class="brand-text font-weight-light">TopNews</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user panel (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="~/Dashboard/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
            </div>
            <div class="info">
                <a href="#" class="d-block">Alexander Pierce</a>
            </div>
        </div>

        <!-- SidebarSearch Form -->
        <div class="form-inline">
            <div class="input-group" data-widget="sidebar-search">
                <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
                <div class="input-group-append">
                    <button class="btn btn-sidebar">
                        <i class="fas fa-search fa-fw"></i>
                    </button>
                </div>
            </div>
        </div>

        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <!-- Add icons to the links using the .nav-icon class
                                     with font-awesome or any other icon font library -->
                <li class="nav-item">
                    <a href="#" class="nav-link active">
                        <i class="nav-icon fas fa-users"></i>
                        <p>
                            Users
                            <i class="fas fa-angle-left right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a asp-controller="Dashboard"  asp-action="GetAll" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>All users</p>
                            </a>
                        </li>
                        @if (@User.IsInRole("Administrator"))
                        {   
                        <li class="nav-item">
                            <a asp-controller="Dashboard" asp-action="AddNew" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Add new</p>
                            </a>
                        </li>
                        }
                    </ul>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link active">
                        <i class="nav-icon fas fa-th"></i>
                        <p>
                            Categories
                            <i class="fas fa-angle-left right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a asp-controller="Category" asp-action="Index" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>All categories</p>
                            </a>
                        </li>
                        @if (@User.IsInRole("Administrator"))
                        {
                            <li class="nav-item">
                                <a asp-controller="Category" asp-action="AddNew" class="nav-link">
                                    <i class="far fa-circle nav-icon"></i>
                                    <p>Add new</p>
                                </a>
                            </li>
                        }
                    </ul>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link active">          
                        <i class="nav-icon fas fa-comments"></i>
                        <p>
                            Posts
                            <i class="fas fa-angle-left right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a asp-controller="Post" asp-action="Index" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>All post</p>
                            </a>
                        </li>
                        @if (@User.IsInRole("Administrator"))
                        {
                            <li class="nav-item">
                                <a asp-controller="Post" asp-action="AddPost" class="nav-link">
                                    <i class="far fa-circle nav-icon"></i>
                                    <p>Add new</p>
                                </a>
                            </li>
                        }
                    </ul>
                </li>
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>